services:
  dreamydormouse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dreamydormouse
    volumes:
      # Persistent storage for RAG data
      - ./rag_storage:/app/rag_storage
      # Output directory for parsed documents
      - ./output:/app/output
      # Mount your markdown files here
      - ./data:/app/data:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-large}
      - EMBEDDING_DIM=${EMBEDDING_DIM:-3072}
    stdin_open: true
    tty: true
