name: Docker Build and Test

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Add timeout to prevent hanging forever

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        timeout-minutes: 40  # Add timeout for build step
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: dreamydormouse:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Add build progress output
          outputs: type=docker

      - name: Check image size
        run: |
          echo "Image size:"
          docker images dreamydormouse:test --format "{{.Size}}"

      - name: Verify uv installation
        run: |
          echo "Checking uv version..."
          docker run --rm dreamydormouse:test uv --version

      - name: Verify Python environment
        run: |
          echo "Checking Python version..."
          docker run --rm dreamydormouse:test python --version

      - name: Show help output
        run: |
          echo "Testing CLI help..."
          docker run --rm dreamydormouse:test

      - name: List installed packages
        run: |
          echo "Listing installed packages..."
          docker run --rm dreamydormouse:test python -m pip list | head -50

